version: "3"

services:
  apache:
    build: 
      context: ./build/apache
    container_name: 'apache'
    restart: 'always'
    ports:
      - "${HTTP_HOST_PORT}:80"
      - "${HTTPS_HOST_PORT}:443"
    networks:
      - frontend
      - backend
    depends_on:
      - mariadb
      - php
      #- pika
      - solr
    volumes: 
      - ${DOCUMENT_ROOT-./html}:/usr/local/apache2/htdocs
      - ./config/vhosts/vhosts.apache.conf:/usr/local/apache2/conf/vhosts.apache.conf
      - ./logs/apache2:/usr/local/apache2/logs

  php:
    build: 
      context: ./build/php
    container_name: 'php'
    networks:
      - backend
    volumes: 
      # TODO: NEED A GOOD php.ini
      #- ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini 
      - ${DOCUMENT_ROOT-./html}:/usr/local/apache2/htdocs

  java:
    build:
      context: ./build/java    
    container_name: 'java'
    networks:
        - backend
        - frontend
    volumes:
      - ${DOCUMENT_ROOT-./html}:/usr/local/apache2/htdocs

  solr:
    build: 
      context: ./build/solr
    container_name: 'solr'
    networks:
      - backend
      - frontend
    ports:
      - "${HOST_SOLR_1_PORT}:8983"
    volumes:
      - ./data/solr:/var/solr
    command:
      - solr-precreate
      - gettingstarted
      
  mariadb:
    build: 
      context: ./build/mariadb
    container_name: 'mariadb'
    restart: 'always'
    ports: 
      - "${HOST_MYSQL_PORT}:3306"
    networks:
      - backend
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  memcached:
    container_name: 'memcached'
    image: memcached:1.5-alpine
    networks: 
      - backend
    ports:
      - "${HOST_MEMCACHED_PORT}:11211"

  #pika:
  #  build:
  #    context: ./build/pika
  #  container_name: 'pika'

networks:
  frontend:
  backend: